version: '3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_NAME=p14_db
      - POSTGRES_USER=p14_db_admin
      - POSTGRES_PASSWORD=p14_db_admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
      - celery
      - redis

  db:
    image: postgres:15.3-alpine
    container_name: db
    environment:
      - POSTGRES_NAME=p14_db
      - POSTGRES_USER=p14_db_admin
      - POSTGRES_PASSWORD=p14_db_admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    command: celery -A RestProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
volumes:
  pg_data:
  redis_data: