# Generated by Django 4.2.6 on 2023-11-06 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneIDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('ctzn', models.CharField(blank=True, max_length=255, null=True)),
                ('per_adr', models.CharField(max_length=255)),
                ('tin', models.CharField(blank=True, max_length=9, null=True)),
                ('pport_issue_place', models.CharField(blank=True, max_length=255, null=True)),
                ('sur_name', models.CharField(max_length=255)),
                ('gd', models.IntegerField(blank=True, null=True)),
                ('natn', models.CharField(blank=True, max_length=255, null=True)),
                ('pport_issue_date', models.DateField(blank=True, null=True)),
                ('pport_expr_date', models.DateField(blank=True, null=True)),
                ('pport_no', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=14)),
                ('mob_phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('mid_name', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=1)),
                ('sess_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ret_cd', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OneIDLegalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_tin', models.CharField(max_length=9)),
                ('tin', models.CharField(max_length=9)),
                ('legal_name', models.TextField()),
                ('acron_uz', models.TextField()),
                ('is_basic', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_id.oneidprofile')),
            ],
        ),
    ]
